site_name: My Docs
site_url: https://github.com/mvishwa27/MkDocs_Project1
nav:
   - Home: index.md
   - About: about.md
   - Iris: 
         - iris1.md
         - iris2.md
         - iris3:
                - iris3.1.md
                - iris3.2.md
         - iris4:
                - iris/iris4/iris4.1.md         
         - iris5:
                - iris/iris5/iris5.1.md
         


theme:
  name: material

# theme: readthedocs

# Copyright
copyright: Copyright &copy; 2022, V$V Technologies Limited
   
