site_name: My Docs
site_url: https://github.com/mvishwa27/MkDocs_Project1
nav:
   - Home: index.md
   - About: about.md

theme:
  name: material

# theme: readthedocs

# Copyright
copyright: Copyright &copy; 2022, V$V Technologies Limited
   
