site_name: My Docs
site_url: https://github.com/mvishwa27/MkDocs_Project1
nav:
   - Home: index.md
   - About: about.md
   - Iris: 
         - iris1.md
         - iris2.md
         - iris3:
                - iris3.1.md
                - iris3.2.md
         - iris4:
                - iris/iris4/iris4.1.md         
         - iris5:
                - iris/iris5/iris5.1.md

# Repository
repo_name: https://github.com/mvishwa27
repo_url: https://github.com/mvishwa27/MkDocs_Project1



# Configuration

theme:
   name: material
   # features:
      # - navigation.tabs
      # - navigation.sections
      # - toc.integrate
   #    - navigation.top
   language: en
   palette:
      - scheme: default
        toggle: 
          icon: material/toggle-switch-off-outline
          name: Switch to dark mode 
        primary: blue
        accent: purple       
      - scheme: slate
        toggle: 
          icon: material/toggle-switch
          name: Switch to light mode 
        primary: teal
        accent: lime 

extra: 
   social:
      - icon: fontawesome/brands/github-alt
        link: https://github.com/mvishwa27 
      - icon: fontawesome/brands/github-alt
        link: https://github.com/mvishwa27 

 
# plugins:
#    - search



# Copyright
copyright: Copyright &copy; 2022, V$V Technologies Limited <a href="https://github.com/mvishwa27">(VISHWA)</a>

# theme name: readthedocs



   
